services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=jayang'
      - 'RABBITMQ_ERLANG_COOKIE=RabbitMQ-Cookies'
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # Web UI port
      - "61613:61613" # STOMP port
      - "15674:15674" # Web STOMP port

  redis:
    image: 'redis:latest'
    container_name: redis
    command: redis-server --requirepass jayang
    ports:
      - '32768:6379'
    labels:
      - "name=redis"
      - "mode=standalone"
