services:
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: 'redis:latest'
    container_name: redis
    command: redis-server --requirepass jayang
    ports:
      - '32768:6379'

